# Workflow definiton
name: "Deploy" 
# Trigger definition
on: 
    push: 
        branches: ["main"]
# Jobs definitions 
# Jobs run on paralel form
jobs:
    deploy-bootcamp:
        # Runner definition: Where our workflows run 
        runs-on: ubuntu-lastest
        steps:
            # Dowload our repository and changes in the runner
            # - uses: actions/checkout@v4
            - run: echo "Pull our code 😎"
            - run: echo "Run migrations 🤪"
            - run: echo "Compile our code"
            - run: echo "New Release "
